### ISSUE TITLE
适配请求：com.tencent.mm

### ISSUE THREAD

**Issue by LX1639193100** [AutoAccountingOrg/AutoRule#262]
```
{"title":"哼","text":"[转账] 请收款"}
```

**Comment by LX1639193100** [comment]
就是他识别不到金额，只有一个这个，通知，数据里面都没有，只有一个这个，不是要让写规则，是反馈一下

**Comment by AnkioTomas** [comment]
> 就是他识别不到金额，只有一个这个，通知，数据里面都没有，只有一个这个，不是要让写规则，是反馈一下

抓的通知本来就没有金额，微信现在还不支持转账的识别
