### ISSUE TITLE
适配请求：com.eg.android.AlipayGphone

### ISSUE THREAD

**Issue by stsiao** [AutoAccountingOrg/AutoRule#399]
## 数据链接                        
[数据过期时间：2024-12-08 11:38:54](https://fars.ee/yJIm)
## 其他信息
可能与银行卡公众号消息识别冲突。目前可以匹配到工行公众号的支出规则，进而记录为支出一笔1.88元

**Comment by AnkioTomas** [comment]
手动忽略就好了~
