### ISSUE TITLE
适配请求 - 微信8.0.49

### ISSUE THREAD

**Issue by timelic** [AutoAccountingOrg/AutoRule#474]
目前测试是转账、红包都是无法识别的状态。

我知道我可以升级微信版本，但是因为微x插件暂时未适配新版本，我相信也有一部分人因为各种原因停留在8.0.49版本，所以可能稍微适配一下比较好。

**Comment by AnkioTomas** [comment]
只是转账和红包有点小问题而已，没时间修。
其他又不影响。
