### ISSUE TITLE
适配请求：com.tencent.mm

### ISSUE THREAD

**Issue by happyhaha1** [AutoAccountingOrg/AutoRule#538]
## 数据链接                        
[数据过期时间：2025-01-27 11:17:02](https://fars.ee/z80e)
## 其他信息
微信版本8.0.54

**Comment by TrioTea** [comment]
在没有更新微信的情况下，转账数据也变成了类似的

**Comment by AnkioTomas** [comment]
没什么问题，这就是转账数据

**Comment by TrioTea** [comment]
> 没什么问题，这就是转账数据

嗯嗯，新搞的这个机器人不错，一个一个点开测试，人都麻了

**Comment by AnkioTomas** [comment]
> > 没什么问题，这就是转账数据
> 
> 嗯嗯，新搞的这个机器人不错，一个一个点开测试，人都麻了

这个一直都有的，他们提交issue就开始尝试做匹配了，现在所有打开的issue都是他们提交的时候没有匹配到规则的

**Comment by TrioTea** [comment]
> 这个一直都有的，他们提交issue就开始尝试做匹配了，现在所有打开的issue都是他们提交的时候没有匹配到规则的

原来如此，可不可以搞个有新commit的时候，自动测试所有issue中的数据，关闭同类型的数据

**Comment by AnkioTomas** [comment]
> > 这个一直都有的，他们提交issue就开始尝试做匹配了，现在所有打开的issue都是他们提交的时候没有匹配到规则的
> 
> 原来如此，可不可以搞个有新commit的时候，自动测试所有issue中的数据，关闭同类型的数据

可
