### ISSUE TITLE
适配请求：com.android.phone

### ISSUE THREAD

**Issue by TOMhongshu** [AutoAccountingOrg/AutoRule#573]
## 数据链接                        
[数据过期时间：2025-02-03 21:56:19](https://fars.ee/_JSR)

**Comment by TrioTea** [comment]
请问，这里的支取，指得是从银行卡支取成现金还是单纯的消费了45元？

**Comment by TOMhongshu** [comment]
这个是银行卡支出，支付了45元后剩余4500元






清欢
***@***.***
