### ISSUE TITLE
适配请求：com.android.phone

### ISSUE THREAD

**Issue by MaYeah233** [AutoAccountingOrg/AutoRule#650]
## 数据链接                        
[数据过期时间：2025-02-27 16:55:33](https://fars.ee/fy07)
## 其他信息

中文双引号是我自己加的

**Comment by AnkioTomas** [comment]
脱敏的时候不要污染数据。
金额可以用0.01这种代替，卡号可以用1234这种代替，要保持原有的结构不变。
